### ISSUE TITLE
interfering with pickerview

### ISSUE THREAD

**Issue by hbmtw** [shaps80/iMessageStyleReveal#1]
For some reason, it is interfering with the pan gesture (scrolling) of the UIPickerview... it does not allow it to scroll... although selection per tap is possible... could not figure out why.

**Comment by SeiryuZ** [comment]
Hi, I also face same issue with UITableView not able to scroll.

**Comment by shaps80** [comment]
This should have been fixed in last update. Can you confirm which version you're using atm?

**Comment by shaps80** [comment]
I have fixed this recently as suggested by iPhone Prolix.

Will release an update soon.
