### ISSUE TITLE
Objective-c support

### ISSUE THREAD

**Issue by mbLc** [shaps80/iMessageStyleReveal#13]
Hi,

I just discovered your work and I wanted to test it with objective-c but I can't make it work. It's the first time I try to import a swift framework into an objective-c project so the problem might come from me.

I added the framework to my Podfile and then I did `@import RevealableCell` I got a `module RevealableCell not found`.

I tried `@import SPXRevealableView;` but after I can't subclass the cell as `RevealableTableViewCell`.

What am I doing wrong?

Thank you for your help

**Comment by shaps80** [comment]
Since this is an old issue and the library has changed since I'm closing this ticket.

Apologies that I never saw this ticket and responded. Hope you got it sorted in the end. :)

**Comment by VivekGoswami** [comment]
How can i get this demo for objective-c?

**Comment by shaps80** [comment]
The included demo is written in Swift. But the code is pretty straight forward. You basically just need to register and dequeue a reusable RevealableView and then configure it per indexPath. Similarly to how you use/configure UITableViewCell's.
