### ISSUE TITLE
No such module 'RevelableCell'

### ISSUE THREAD

**Issue by surajshrestha** [shaps80/iMessageStyleReveal#16]
The project guideline suggest to add this pod file 'SPXRevealableView' and afterward import this class @import RevealableCell. I did the same but I cant import the class in my project it says 'No such module 'RevelableCell''. 
Well the other thing that i notice is after installing the pod file all the folder get downloaded except this folder name Development Pods.
I have attach screenshot of my pod file also the list of folder that has been downloaded after installing the pod file.
Please give a look.
![screen shot 2017-02-21 at 12 32 47 pm](https://cloud.githubusercontent.com/assets/4495476/23153721/221b15d6-f832-11e6-9e01-2875d6ffd35b.png)
![screen shot 2017-02-21 at 12 34 10 pm](https://cloud.githubusercontent.com/assets/4495476/23153736/3afee3b6-f832-11e6-84ff-5bcdb6e962d0.png)

.

**Comment by shaps80** [comment]
I took a look and I see your issue now.

In your Pod file you should be using the new version:

`pod 'RevealableCell'`

Sorry about that, but I changed this some time ago, SPXRevealableView no longer exists ;)

**Comment by shaps80** [comment]
Ok so looking at your Podfile I can see you still have `pod 'SPXRevealableView'` which no longer exists. Or at least it shouldn't. When looking through Cocoapods it does look like its missing `RevealableCell` which is odd. 

Either way I 100% have local changes that I've never committed to Cocoapods.

I'm working on a minor update right now and will publish it this morning so you can fetch it.

Thanks for bringing this to my attention.

**Comment by shaps80** [comment]
Quick note, depending on which version you're currently using there may be some API changes. 
Previously you would set the revealable view on the cell directly. However this was terribly inefficient particularly with large lists.

So, the API has been updated now and includes a reuse queue. The README and Example app are best to checkout how to use this. Its really straightforward though and should require minimal change on your part if necessary.

**Comment by shaps80** [comment]
Ok, so I've fixed everything and it should now work as expected. Please use the following:

If you need Swift 2.2:
`pod 'RevealableCell', '1.1'`

If you need Swift 3.0:
`pod 'RevealableCell', '2.0'`
