### ISSUE TITLE
Timestamp view remains on UItableViewCell when we scroll the table with timestamp view open 

### ISSUE THREAD

**Issue by RajanMaheshwari** [shaps80/iMessageStyleReveal#19]
When we swipe left to open the timestamp view and we scroll the table very fast with the timestamp view as opened(keeping the thumb on screen), it will try to slide right but doesn't get closed completely in some of the cells, may be due to reusability. Note that the number of cells should be more (for ex 20). And after that if we provide a right swipe, then they disappear. Any quick fix?

![simulator screen shot 13-jun-2017 5 58 50 pm](https://user-images.githubusercontent.com/6380389/27082370-0f529b08-5062-11e7-92b2-669737fe4d5d.png)
![simulator screen shot 13-jun-2017 5 59 20 pm](https://user-images.githubusercontent.com/6380389/27082368-0f4ea458-5062-11e7-84a7-724c6d9623b6.png)
![simulator screen shot 13-jun-2017 5 59 25 pm](https://user-images.githubusercontent.com/6380389/27082369-0f510892-5062-11e7-8725-0a67fc9df468.png)

**Comment by RajanMaheshwari** [comment]
However commenting out lines **150-152** in **UITableView+Extension** fix the issue. But it removes dequeue functionality.
```
if let view = queue.dequeueView() {
    return view
}
```

**Comment by shaps80** [comment]
Sorry I’m only just seeing this now. You could check where I call prepareForReuse on the reusable view and possibly reset it’s frame or invalidate the layout. I haven’t got time right now to check this myself.

**Comment by asifbilal786** [comment]
I am facing the same issue and did reset the frame in prepareForReuse but didn't resolve it.

Please help me to resolve this issue.

**Comment by RajanMaheshwari** [comment]
@asifbilal786  Comment the lines 150-152 in UITableView+Extension as suggested in my comment of 13 Jun. It removes the dequeue functionality though.

**Comment by asifbilal786** [comment]
Thanks @Rajan but I think commenting above mentioned lines would remove the deque functionality and I don't wanna miss that

**Comment by RajanMaheshwari** [comment]
@asifbilal786 Yes, I already stated that it will remove the dequeue functionality. You can write some sort of logic in your `cellForRow` method where you can assign a tag to this and remove it everytime in the beginning from the superview.

**Comment by fawzirifai** [comment]
Guys did you find a fix for this?

**Comment by shaps80** [comment]
Feel free to submit a PR. (Also see my notes on your other comment)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ravishankar-dale** [comment]
Transforming the view to identity before reuse worked for me. This will bring back the view to default state and also we can still use dequeue functionality.
if let view = queue.dequeueView() {
    view.transform = .identity
    return view
 }

**Comment by shaps80** [comment]
Oh that makes sense, I'll make a release with that fix. Thanks @ravishankar-dale

**Comment by shaps80** [comment]
Actually @ravishankar-dale I just realised I'm already doing this internally as a part of the reuse. I also removeFromSuperview which I believe would cause a reset anyway.

**Comment by shaps80** [comment]
Ok, just gave that a shot and I think it fixes it.

**Comment by shaps80** [comment]
Fix applied and Xcode 11/Swift 5.1 now out.
