### ISSUE TITLE
Jumpy revealable cells when using `contentInsetAdjustmentBehavior` never

### ISSUE THREAD

**Issue by brod-ie** [shaps80/iMessageStyleReveal#20]
We're using [SlackTextViewControlle](https://github.com/slackhq/SlackTextViewController) for our Chat UI. Due to UIScrollView inset changes in iOS 11, they recommend using

```
if #available(iOS 11.0, *) {
    tableView!.contentInsetAdjustmentBehavior = .never
}
```
 to remove the unsightly bottom padding.

# Before:

![always](https://user-images.githubusercontent.com/1520630/31180040-73541a12-a915-11e7-9f0e-338ff21cc4bf.gif)

# After (ignore colour):

![never](https://user-images.githubusercontent.com/1520630/31180039-730a4f36-a915-11e7-809d-e0518b1e351b.gif)

The revealable cells now jump. How can I fix this?

**Comment by brod-ie** [comment]
`automaticallyAdjustsScrollViewInsets` is set to false too

**Comment by juanjold** [comment]
I've encountered this same issue. Did you manage to find a fix?
