### ISSUE TITLE
Update code for swift 4

### ISSUE THREAD

**Issue by dmyma** [shaps80/iMessageStyleReveal#22]
I am using iMessageStyleReveal, there are three lines of code that I need to manually update to compile with swift 4, is it possible to update iMessageStyleReveal to compile with swift 4, I can do that if you let me do it.

1. let associatedProperty = UIPanGestureRecognizer(target: self, action: #selector(UITableView.handleRevealPan(_:)))
- add objC to the funciton

2. let viewAttribute: NSLayoutAttribute = direction == .left ? .left : .right 
- convert to: let viewAttribute: NSLayoutConstraint.Attribute = direction == .left ? .left : .right

3. let parentAttribute: NSLayoutAttribute = direction == .left ? .right : .left
- convert to: let parentAttribute: NSLayoutConstraint.Attribute = direction == .left ? .right : .left

**Comment by hggz** [comment]
https://github.com/hggz/iMessageStyleReveal

I made a swift 5 compatible fork above ^

**Comment by shaps80** [comment]
Swift 5.1 and Xcode 11 officially supported now. Sorry its late.
