### ISSUE TITLE
Is it possible to have it for one tableview only?

### ISSUE THREAD

**Issue by mastermyx** [shaps80/iMessageStyleReveal#9]
Hello,

I have a big app using a lots of tableviews. I really love your work but I need it to use it in only one tableview. It actually interacts with all my others tableviews gestures and it breaks some actions i wanted to keep. I tried to changed your code but I didn't find out how to resolve it. 

So my question is:
Is it possible to have this iMessageStyleReveal working only on one tableview (i mean no interaction with gesture at all with other tableview)? 

Thank you,
Arthur

**Comment by DKalachniuk** [comment]
I had the same issue. to your other table views make the same setup [self.tableView enableRevealableViewForDirection:SPXRevealableViewGestureDirectionLeft];
but 
cell.revealableView =nil;

for that table views

**Comment by mastermyx** [comment]
I find out how do it before your answer DK, but thank you!

I subclass as MyTableView instead of UITableView in his class and it works!
